version: "3"
services:
  jk_master:
    build: jenkins_master
    restart: always
#   volumes:
#     - ./backup:/backup
#    volumes_from:
#      - jk_data
#      - api_docs_data:rw
#    ports:
#      - "50000:50000"
#      - "8080:8080" # Jun Jenins publicly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jk_data:/var/jenkins_home
      - jk_data:/apidata
    tty: true
    expose:
      - "50000"
      - "8080"

  jk_nginx:
    build: jenkins_nginx
    # Requires a .env file containing at least the line: JENKINS_PORT=8444.
    # HOST:CONTAINER
    ports:
      - "8080:${JENKINS_PORT}"
    environment:
      - JENKINS_PORT=${JENKINS_PORT}
      - JENKINS_HOST=${JENKINS_HOST}
    depends_on:
      - jk_master
    links:
      - jk_master


#  https://github.com/jwilder/nginx-proxy
#  docker run  -p 8444:80 -e VIRTUAL_HOST=foo.bar.com -e VIRTUAL_PORT=8444 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy:alpine
#  jk_nginx:
#   build: jenkins_nginx
#   # Requires a .env file containing at least the line: JENKINS_PORT=8444.
#   ports:
#     - "${JENKINS_PORT}:80"
#   volumes:
#     - /var/run/docker.sock:/tmp/docker.sock:ro

  api_docs:
    build: api_docs
    restart: always
    # Requires a .env file containing at least the line: API_PORT=8444.
    ports:
      - "${API_PORT}:80"
    volumes:
      - api_docs_data:/apidocs
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}

  jk_data:
     build: jenkins_data
     tty: true

  api_docs_data:
    build: api_docs_data
    tty: true

volumes:
  jk_data:
  api_docs_data:
