jk_master:
  build: jenkins_master
  restart: always
  volumes:
    - ./backup:/backup
  volumes_from:
    - jk_data
    - api_docs_data:rw
  ports:
    - "50000:50000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  tty: true
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${JENKINS_PORT}

jk_data:
 build: jenkins_data

#jk_nginx:
# build: jenkins_nginx
# # Requires a .env file containing at least the line: JENKINS_PORT=8444.
# ports:
#    - "${JENKINS_PORT}:80"
# links:
#    - jk_master:jenkins_master

# https://github.com/jwilder/nginx-proxy
# docker run  -p 8444:80 -e VIRTUAL_HOST=foo.bar.com -e VIRTUAL_PORT=8444 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy:alpine
jk_nginx:
  build: jenkins_nginx
  # Requires a .env file containing at least the line: JENKINS_PORT=8444.
  ports:
    - "${JENKINS_PORT}:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

api_docs:
  build: api_docs
  restart: always
  # Requires a .env file containing at least the line: API_PORT=8444.
  ports:
    - "${API_PORT}:80"
  volumes_from:
    - api_docs_data:ro

api_docs_data:
 build: api_docs_data

# TODO: MIGRATE to version 3 standard.

# https://github.com/hrektts/docker-doxygen/blob/master/Dockerfile
