FROM jrelva/nginx-autoindex

  # https://hub.docker.com/r/jrelva/nginx-autoindex/
  # image: jrelva/nginx-autoindex

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

# docker build -t ethereum-php-doc --no-cache .
# docker run --name ethereum-php-doc-ngnix -p 8080:80  ethereum-php-doc
# docker run --name docker-nginx -p 8080:80 nginx
# docker run --name docker-nginx -p 8080:80  -v /Users/tho/htdocs/ConsenSys/DocumentationDocker/htdocs/:/usr/share/nginx/html:ro nnxn
# -->  http://192.168.99.100:8080/
